# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import my_api.utils.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 9, 11, 15, 15, 666614, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 9, 11, 15, 15, 666614, tzinfo=utc))),
                ('nome', my_api.utils.widgets.UpperCharField(max_length=100, verbose_name='Nome')),
                ('data_inicio', models.DateField(null=True, verbose_name='Data In\xedcio')),
                ('data_fim', models.DateField(null=True, verbose_name='Data Fim')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
