# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-04 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import m2agro.utils.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_basico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 9, 11, 15, 15, 666614, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 9, 11, 15, 15, 666614, tzinfo=utc))),
                ('nome', m2agro.utils.widgets.UpperCharField(max_length=100, unique=True, verbose_name='Nome')),
                ('data_inicio', models.DateField(null=True, verbose_name='Data In\xedcio')),
                ('data_fim', models.DateField(null=True, verbose_name='Data Fim')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Custo Total')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basico.Safra')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Servi\xe7o',
                'verbose_name_plural': 'Servi\xe7os',
            },
        ),
        migrations.CreateModel(
            name='ServicoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 9, 11, 15, 15, 666614, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 9, 11, 15, 15, 666614, tzinfo=utc))),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('custo_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_itens', to='api_basico.Produto')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_itens', to='api_servico.Servico')),
            ],
            options={
                'ordering': ['produto__nome'],
                'verbose_name': 'Item de Servi\xe7o',
                'verbose_name_plural': 'Itens de Servi\xe7os',
            },
        ),
    ]
