# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-04 01:14
from __future__ import unicode_literals

from django.db import migrations
import m2agro.utils.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('api_servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=m2agro.utils.widgets.UpperCharField(max_length=100, verbose_name='Nome'),
        ),
    ]
