# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_servico', '0003_servicoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicoitem',
            options={'ordering': ['produto__nome'], 'verbose_name': 'Item de Servi\xe7o', 'verbose_name_plural': 'Itens de Servi\xe7os'},
        ),
    ]
