# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='safra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='safra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
